In [2]:
import eikon as ek
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = 'browser'

In [3]:
ek.set_app_key("e943b97f0ced4c0196e8f5fd2e1527b53f6803a7")

In [ ]:
df = pd.read_csv("all_yield_data(big).csv")

In [5]:
df.head()

,KEY,FREQ,REF_AREA,CURRENCY,PROVIDER_FM,INSTRUMENT_FM,PROVIDER_FM_ID,DATA_TYPE_FM,TIME_PERIOD,OBS_VALUE,...,UNIT_INDEX_BASE,COMPILATION,COVERAGE,DECIMALS,SOURCE_AGENCY,SOURCE_PUB,TITLE,TITLE_COMPL,UNIT,UNIT_MULT
0,YC.B.U2.EUR.4F.G_N_A.SV_C_YM.BETA0,B,U2,EUR,4F,G_N_A,SV_C_YM,BETA0,2004-09-06,5.410510,...,NaN,NaN,NaN,6,NaN,NaN,"Yield curve parameters, Beta 0 - Government bo...",Euro area (changing composition) - Government ...,PURE_NUMB,0
1,YC.B.U2.EUR.4F.G_N_A.SV_C_YM.BETA0,B,U2,EUR,4F,G_N_A,SV_C_YM,BETA0,2004-09-07,5.391886,...,NaN,NaN,NaN,6,NaN,NaN,"Yield curve parameters, Beta 0 - Government bo...",Euro area (changing composition) - Government ...,PURE_NUMB,0
2,YC.B.U2.EUR.4F.G_N_A.SV_C_YM.BETA0,B,U2,EUR,4F,G_N_A,SV_C_YM,BETA0,2004-09-08,5.385978,...,NaN,NaN,NaN,6,NaN,NaN,"Yield curve parameters, Beta 0 - Government bo...",Euro area (changing composition) - Government ...,PURE_NUMB,0
3,YC.B.U2.EUR.4F.G_N_A.SV_C_YM.BETA0,B,U2,EUR,4F,G_N_A,SV_C_YM,BETA0,2004-09-09,5.377333,...,NaN,NaN,NaN,6,NaN,NaN,"Yield curve parameters, Beta 0 - Government bo...",Euro area (changing composition) - Government ...,PURE_NUMB,0
4,YC.B.U2.EUR.4F.G_N_A.SV_C_YM.BETA0,B,U2,EUR,4F,G_N_A,SV_C_YM,BETA0,2004-09-10,5.355732,...,NaN,NaN,NaN,6,NaN,NaN,"Yield curve parameters, Beta 0 - Government bo...",Euro area (changing composition) - Government ...,PURE_NUMB,0

In [6]:
df.shape

(5626543, 40)

In [7]:
df.columns

Index(['KEY', 'FREQ', 'REF_AREA', 'CURRENCY', 'PROVIDER_FM', 'INSTRUMENT_FM',
       'PROVIDER_FM_ID', 'DATA_TYPE_FM', 'TIME_PERIOD', 'OBS_VALUE',
       'OBS_STATUS', 'OBS_CONF', 'OBS_PRE_BREAK', 'OBS_COM', 'TIME_FORMAT',
       'BREAKS', 'COLLECTION', 'COMPILING_ORG', 'DISS_ORG', 'DOM_SER_IDS',
       'FM_CONTRACT_TIME', 'FM_COUPON_RATE', 'FM_IDENTIFIER', 'FM_LOT_SIZE',
       'FM_MATURITY', 'FM_OUTS_AMOUNT', 'FM_PUT_CALL', 'FM_STRIKE_PRICE',
       'PUBL_MU', 'PUBL_PUBLIC', 'UNIT_INDEX_BASE', 'COMPILATION', 'COVERAGE',
       'DECIMALS', 'SOURCE_AGENCY', 'SOURCE_PUB', 'TITLE', 'TITLE_COMPL',
       'UNIT', 'UNIT_MULT'],
      dtype='object')

In [8]:
df_filtered = df[['TIME_PERIOD', 'DATA_TYPE_FM', 'OBS_VALUE']]

In [9]:
df_filtered.tail()

        TIME_PERIOD DATA_TYPE_FM  OBS_VALUE
5626538  2024-12-20         TAU2  11.291386
5626539  2024-12-23         TAU2  11.181443
5626540  2024-12-24         TAU2  11.157284
5626541  2024-12-27         TAU2  11.226826
5626542  2024-12-30         TAU2  11.263171

In [10]:
unique_values = df['DATA_TYPE_FM'].unique()
for i in range(len(unique_values)):
    print(unique_values[i])

BETA0
BETA1
BETA2
BETA3
IF_10M
IF_10Y
IF_10Y10M
IF_10Y11M
IF_10Y1M
IF_10Y2M
IF_10Y3M
IF_10Y4M
IF_10Y5M
IF_10Y6M
IF_10Y7M
IF_10Y8M
IF_10Y9M
IF_11M
IF_11Y
IF_11Y10M
IF_11Y11M
IF_11Y1M
IF_11Y2M
IF_11Y3M
IF_11Y4M
IF_11Y5M
IF_11Y6M
IF_11Y7M
IF_11Y8M
IF_11Y9M
IF_12Y
IF_12Y10M
IF_12Y11M
IF_12Y1M
IF_12Y2M
IF_12Y3M
IF_12Y4M
IF_12Y5M
IF_12Y6M
IF_12Y7M
IF_12Y8M
IF_12Y9M
IF_13Y
IF_13Y10M
IF_13Y11M
IF_13Y1M
IF_13Y2M
IF_13Y3M
IF_13Y4M
IF_13Y5M
IF_13Y6M
IF_13Y7M
IF_13Y8M
IF_13Y9M
IF_14Y
IF_14Y10M
IF_14Y11M
IF_14Y1M
IF_14Y2M
IF_14Y3M
IF_14Y4M
IF_14Y5M
IF_14Y6M
IF_14Y7M
IF_14Y8M
IF_14Y9M
IF_15Y
IF_15Y10M
IF_15Y11M
IF_15Y1M
IF_15Y2M
IF_15Y3M
IF_15Y4M
IF_15Y5M
IF_15Y6M
IF_15Y7M
IF_15Y8M
IF_15Y9M
IF_16Y
IF_16Y10M
IF_16Y11M
IF_16Y1M
IF_16Y2M
IF_16Y3M
IF_16Y4M
IF_16Y5M
IF_16Y6M
IF_16Y7M
IF_16Y8M
IF_16Y9M
IF_17Y
IF_17Y10M
IF_17Y11M
IF_17Y1M
IF_17Y2M
IF_17Y3M
IF_17Y4M
IF_17Y5M
IF_17Y6M
IF_17Y7M
IF_17Y8M
IF_17Y9M
IF_18Y
IF_18Y10M
IF_18Y11M
IF_18Y1M
IF_18Y2M
IF_18Y3M
IF_18Y4M
IF_18Y5M
IF_18Y6M
IF_18Y7M
IF_18Y8M
IF_18Y9M
IF_19Y
IF_19Y10M
IF_19Y11M
IF_19Y1M
IF_19Y2M
IF_19Y3M
IF_19Y4M
IF_19Y5M
IF_19Y6M
IF_19Y7M
IF_19Y8M
IF_19Y9M
IF_1Y
IF_1Y10M
IF_1Y11M
IF_1Y1M
IF_1Y2M
IF_1Y3M
IF_1Y4M
IF_1Y5M
IF_1Y6M
IF_1Y7M
IF_1Y8M
IF_1Y9M
IF_20Y
IF_20Y10M
IF_20Y11M
IF_20Y1M
IF_20Y2M
IF_20Y3M
IF_20Y4M
IF_20Y5M
IF_20Y6M
IF_20Y7M
IF_20Y8M
IF_20Y9M
IF_21Y
IF_21Y10M
IF_21Y11M
IF_21Y1M
IF_21Y2M
IF_21Y3M
IF_21Y4M
IF_21Y5M
IF_21Y6M
IF_21Y7M
IF_21Y8M
IF_21Y9M
IF_22Y
IF_22Y10M
IF_22Y11M
IF_22Y1M
IF_22Y2M
IF_22Y3M
IF_22Y4M
IF_22Y5M
IF_22Y6M
IF_22Y7M
IF_22Y8M
IF_22Y9M
IF_23Y
IF_23Y10M
IF_23Y11M
IF_23Y1M
IF_23Y2M
IF_23Y3M
IF_23Y4M
IF_23Y5M
IF_23Y6M
IF_23Y7M
IF_23Y8M
IF_23Y9M
IF_24Y
IF_24Y10M
IF_24Y11M
IF_24Y1M
IF_24Y2M
IF_24Y3M
IF_24Y4M
IF_24Y5M
IF_24Y6M
IF_24Y7M
IF_24Y8M
IF_24Y9M
IF_25Y
IF_25Y10M
IF_25Y11M
IF_25Y1M
IF_25Y2M
IF_25Y3M
IF_25Y4M
IF_25Y5M
IF_25Y6M
IF_25Y7M
IF_25Y8M
IF_25Y9M
IF_26Y
IF_26Y10M
IF_26Y11M
IF_26Y1M
IF_26Y2M
IF_26Y3M
IF_26Y4M
IF_26Y5M
IF_26Y6M
IF_26Y7M
IF_26Y8M
IF_26Y9M
IF_27Y
IF_27Y10M
IF_27Y11M
IF_27Y1M
IF_27Y2M
IF_27Y3M
IF_27Y4M
IF_27Y5M
IF_27Y6M
IF_27Y7M
IF_27Y8M
IF_27Y9M
IF_28Y
IF_28Y10M
IF_28Y11M
IF_28Y1M
IF_28Y2M
IF_28Y3M
IF_28Y4M
IF_28Y5M
IF_28Y6M
IF_28Y7M
IF_28Y8M
IF_28Y9M
IF_29Y
IF_29Y10M
IF_29Y11M
IF_29Y1M
IF_29Y2M
IF_29Y3M
IF_29Y4M
IF_29Y5M
IF_29Y6M
IF_29Y7M
IF_29Y8M
IF_29Y9M
IF_2Y
IF_2Y10M
IF_2Y11M
IF_2Y1M
IF_2Y2M
IF_2Y3M
IF_2Y4M
IF_2Y5M
IF_2Y6M
IF_2Y7M
IF_2Y8M
IF_2Y9M
IF_30Y
IF_3M
IF_3Y
IF_3Y10M
IF_3Y11M
IF_3Y1M
IF_3Y2M
IF_3Y3M
IF_3Y4M
IF_3Y5M
IF_3Y6M
IF_3Y7M
IF_3Y8M
IF_3Y9M
IF_4M
IF_4Y
IF_4Y10M
IF_4Y11M
IF_4Y1M
IF_4Y2M
IF_4Y3M
IF_4Y4M
IF_4Y5M
IF_4Y6M
IF_4Y7M
IF_4Y8M
IF_4Y9M
IF_5M
IF_5Y
IF_5Y10M
IF_5Y11M
IF_5Y1M
IF_5Y2M
IF_5Y3M
IF_5Y4M
IF_5Y5M
IF_5Y6M
IF_5Y7M
IF_5Y8M
IF_5Y9M
IF_6M
IF_6Y
IF_6Y10M
IF_6Y11M
IF_6Y1M
IF_6Y2M
IF_6Y3M
IF_6Y4M
IF_6Y5M
IF_6Y6M
IF_6Y7M
IF_6Y8M
IF_6Y9M
IF_7M
IF_7Y
IF_7Y10M
IF_7Y11M
IF_7Y1M
IF_7Y2M
IF_7Y3M
IF_7Y4M
IF_7Y5M
IF_7Y6M
IF_7Y7M
IF_7Y8M
IF_7Y9M
IF_8M
IF_8Y
IF_8Y10M
IF_8Y11M
IF_8Y1M
IF_8Y2M
IF_8Y3M
IF_8Y4M
IF_8Y5M
IF_8Y6M
IF_8Y7M
IF_8Y8M
IF_8Y9M
IF_9M
IF_9Y
IF_9Y10M
IF_9Y11M
IF_9Y1M
IF_9Y2M
IF_9Y3M
IF_9Y4M
IF_9Y5M
IF_9Y6M
IF_9Y7M
IF_9Y8M
IF_9Y9M
PY_10M
PY_10Y
PY_10Y10M
PY_10Y11M
PY_10Y1M
PY_10Y2M
PY_10Y3M
PY_10Y4M
PY_10Y5M
PY_10Y6M
PY_10Y7M
PY_10Y8M
PY_10Y9M
PY_11M
PY_11Y
PY_11Y10M
PY_11Y11M
PY_11Y1M
PY_11Y2M
PY_11Y3M
PY_11Y4M
PY_11Y5M
PY_11Y6M
PY_11Y7M
PY_11Y8M
PY_11Y9M
PY_12Y
PY_12Y10M
PY_12Y11M
PY_12Y1M
PY_12Y2M
PY_12Y3M
PY_12Y4M
PY_12Y5M
PY_12Y6M
PY_12Y7M
PY_12Y8M
PY_12Y9M
PY_13Y
PY_13Y10M
PY_13Y11M
PY_13Y1M
PY_13Y2M
PY_13Y3M
PY_13Y4M
PY_13Y5M
PY_13Y6M
PY_13Y7M
PY_13Y8M
PY_13Y9M
PY_14Y
PY_14Y10M
PY_14Y11M
PY_14Y1M
PY_14Y2M
PY_14Y3M
PY_14Y4M
PY_14Y5M
PY_14Y6M
PY_14Y7M
PY_14Y8M
PY_14Y9M
PY_15Y
PY_15Y10M
PY_15Y11M
PY_15Y1M
PY_15Y2M
PY_15Y3M
PY_15Y4M
PY_15Y5M
PY_15Y6M
PY_15Y7M
PY_15Y8M
PY_15Y9M
PY_16Y
PY_16Y10M
PY_16Y11M
PY_16Y1M
PY_16Y2M
PY_16Y3M
PY_16Y4M
PY_16Y5M
PY_16Y6M
PY_16Y7M
PY_16Y8M
PY_16Y9M
PY_17Y
PY_17Y10M
PY_17Y11M
PY_17Y1M
PY_17Y2M
PY_17Y3M
PY_17Y4M
PY_17Y5M
PY_17Y6M
PY_17Y7M
PY_17Y8M
PY_17Y9M
PY_18Y
PY_18Y10M
PY_18Y11M
PY_18Y1M
PY_18Y2M
PY_18Y3M
PY_18Y4M
PY_18Y5M
PY_18Y6M
PY_18Y7M
PY_18Y8M
PY_18Y9M
PY_19Y
PY_19Y10M
PY_19Y11M
PY_19Y1M
PY_19Y2M
PY_19Y3M
PY_19Y4M
PY_19Y5M
PY_19Y6M
PY_19Y7M
PY_19Y8M
PY_19Y9M
PY_1Y
PY_1Y10M
PY_1Y11M
PY_1Y1M
PY_1Y2M
PY_1Y3M
PY_1Y4M
PY_1Y5M
PY_1Y6M
PY_1Y7M
PY_1Y8M
PY_1Y9M
PY_20Y
PY_20Y10M
PY_20Y11M
PY_20Y1M
PY_20Y2M
PY_20Y3M
PY_20Y4M
PY_20Y5M
PY_20Y6M
PY_20Y7M
PY_20Y8M
PY_20Y9M
PY_21Y
PY_21Y10M
PY_21Y11M
PY_21Y1M
PY_21Y2M
PY_21Y3M
PY_21Y4M
PY_21Y5M
PY_21Y6M
PY_21Y7M
PY_21Y8M
PY_21Y9M
PY_22Y
PY_22Y10M
PY_22Y11M
PY_22Y1M
PY_22Y2M
PY_22Y3M
PY_22Y4M
PY_22Y5M
PY_22Y6M
PY_22Y7M
PY_22Y8M
PY_22Y9M
PY_23Y
PY_23Y10M
PY_23Y11M
PY_23Y1M
PY_23Y2M
PY_23Y3M
PY_23Y4M
PY_23Y5M
PY_23Y6M
PY_23Y7M
PY_23Y8M
PY_23Y9M
PY_24Y
PY_24Y10M
PY_24Y11M
PY_24Y1M
PY_24Y2M
PY_24Y3M
PY_24Y4M
PY_24Y5M
PY_24Y6M
PY_24Y7M
PY_24Y8M
PY_24Y9M
PY_25Y
PY_25Y10M
PY_25Y11M
PY_25Y1M
PY_25Y2M
PY_25Y3M
PY_25Y4M
PY_25Y5M
PY_25Y6M
PY_25Y7M
PY_25Y8M
PY_25Y9M
PY_26Y
PY_26Y10M
PY_26Y11M
PY_26Y1M
PY_26Y2M
PY_26Y3M
PY_26Y4M
PY_26Y5M
PY_26Y6M
PY_26Y7M
PY_26Y8M
PY_26Y9M
PY_27Y
PY_27Y10M
PY_27Y11M
PY_27Y1M
PY_27Y2M
PY_27Y3M
PY_27Y4M
PY_27Y5M
PY_27Y6M
PY_27Y7M
PY_27Y8M
PY_27Y9M
PY_28Y
PY_28Y10M
PY_28Y11M
PY_28Y1M
PY_28Y2M
PY_28Y3M
PY_28Y4M
PY_28Y5M
PY_28Y6M
PY_28Y7M
PY_28Y8M
PY_28Y9M
PY_29Y
PY_29Y10M
PY_29Y11M
PY_29Y1M
PY_29Y2M
PY_29Y3M
PY_29Y4M
PY_29Y5M
PY_29Y6M
PY_29Y7M
PY_29Y8M
PY_29Y9M
PY_2Y
PY_2Y10M
PY_2Y11M
PY_2Y1M
PY_2Y2M
PY_2Y3M
PY_2Y4M
PY_2Y5M
PY_2Y6M
PY_2Y7M
PY_2Y8M
PY_2Y9M
PY_30Y
PY_3M
PY_3Y
PY_3Y10M
PY_3Y11M
PY_3Y1M
PY_3Y2M
PY_3Y3M
PY_3Y4M
PY_3Y5M
PY_3Y6M
PY_3Y7M
PY_3Y8M
PY_3Y9M
PY_4M
PY_4Y
PY_4Y10M
PY_4Y11M
PY_4Y1M
PY_4Y2M
PY_4Y3M
PY_4Y4M
PY_4Y5M
PY_4Y6M
PY_4Y7M
PY_4Y8M
PY_4Y9M
PY_5M
PY_5Y
PY_5Y10M
PY_5Y11M
PY_5Y1M
PY_5Y2M
PY_5Y3M
PY_5Y4M
PY_5Y5M
PY_5Y6M
PY_5Y7M
PY_5Y8M
PY_5Y9M
PY_6M
PY_6Y
PY_6Y10M
PY_6Y11M
PY_6Y1M
PY_6Y2M
PY_6Y3M
PY_6Y4M
PY_6Y5M
PY_6Y6M
PY_6Y7M
PY_6Y8M
PY_6Y9M
PY_7M
PY_7Y
PY_7Y10M
PY_7Y11M
PY_7Y1M
PY_7Y2M
PY_7Y3M
PY_7Y4M
PY_7Y5M
PY_7Y6M
PY_7Y7M
PY_7Y8M
PY_7Y9M
PY_8M
PY_8Y
PY_8Y10M
PY_8Y11M
PY_8Y1M
PY_8Y2M
PY_8Y3M
PY_8Y4M
PY_8Y5M
PY_8Y6M
PY_8Y7M
PY_8Y8M
PY_8Y9M
PY_9M
PY_9Y
PY_9Y10M
PY_9Y11M
PY_9Y1M
PY_9Y2M
PY_9Y3M
PY_9Y4M
PY_9Y5M
PY_9Y6M
PY_9Y7M
PY_9Y8M
PY_9Y9M
SRS_10Y_1Y
SRS_10Y_2Y
SRS_10Y_3M
SR_10M
SR_10Y
SR_10Y10M
SR_10Y11M
SR_10Y1M
SR_10Y2M
SR_10Y3M
SR_10Y4M
SR_10Y5M
SR_10Y6M
SR_10Y7M
SR_10Y8M
SR_10Y9M
SR_11M
SR_11Y
SR_11Y10M
SR_11Y11M
SR_11Y1M
SR_11Y2M
SR_11Y3M
SR_11Y4M
SR_11Y5M
SR_11Y6M
SR_11Y7M
SR_11Y8M
SR_11Y9M
SR_12Y
SR_12Y10M
SR_12Y11M
SR_12Y1M
SR_12Y2M
SR_12Y3M
SR_12Y4M
SR_12Y5M
SR_12Y6M
SR_12Y7M
SR_12Y8M
SR_12Y9M
SR_13Y
SR_13Y10M
SR_13Y11M
SR_13Y1M
SR_13Y2M
SR_13Y3M
SR_13Y4M
SR_13Y5M
SR_13Y6M
SR_13Y7M
SR_13Y8M
SR_13Y9M
SR_14Y
SR_14Y10M
SR_14Y11M
SR_14Y1M
SR_14Y2M
SR_14Y3M
SR_14Y4M
SR_14Y5M
SR_14Y6M
SR_14Y7M
SR_14Y8M
SR_14Y9M
SR_15Y
SR_15Y10M
SR_15Y11M
SR_15Y1M
SR_15Y2M
SR_15Y3M
SR_15Y4M
SR_15Y5M
SR_15Y6M
SR_15Y7M
SR_15Y8M
SR_15Y9M
SR_16Y
SR_16Y10M
SR_16Y11M
SR_16Y1M
SR_16Y2M
SR_16Y3M
SR_16Y4M
SR_16Y5M
SR_16Y6M
SR_16Y7M
SR_16Y8M
SR_16Y9M
SR_17Y
SR_17Y10M
SR_17Y11M
SR_17Y1M
SR_17Y2M
SR_17Y3M
SR_17Y4M
SR_17Y5M
SR_17Y6M
SR_17Y7M
SR_17Y8M
SR_17Y9M
SR_18Y
SR_18Y10M
SR_18Y11M
SR_18Y1M
SR_18Y2M
SR_18Y3M
SR_18Y4M
SR_18Y5M
SR_18Y6M
SR_18Y7M
SR_18Y8M
SR_18Y9M
SR_19Y
SR_19Y10M
SR_19Y11M
SR_19Y1M
SR_19Y2M
SR_19Y3M
SR_19Y4M
SR_19Y5M
SR_19Y6M
SR_19Y7M
SR_19Y8M
SR_19Y9M
SR_1Y
SR_1Y10M
SR_1Y11M
SR_1Y1M
SR_1Y2M
SR_1Y3M
SR_1Y4M
SR_1Y5M
SR_1Y6M
SR_1Y7M
SR_1Y8M
SR_1Y9M
SR_20Y
SR_20Y10M
SR_20Y11M
SR_20Y1M
SR_20Y2M
SR_20Y3M
SR_20Y4M
SR_20Y5M
SR_20Y6M
SR_20Y7M
SR_20Y8M
SR_20Y9M
SR_21Y
SR_21Y10M
SR_21Y11M
SR_21Y1M
SR_21Y2M
SR_21Y3M
SR_21Y4M
SR_21Y5M
SR_21Y6M
SR_21Y7M
SR_21Y8M
SR_21Y9M
SR_22Y
SR_22Y10M
SR_22Y11M
SR_22Y1M
SR_22Y2M
SR_22Y3M
SR_22Y4M
SR_22Y5M
SR_22Y6M
SR_22Y7M
SR_22Y8M
SR_22Y9M
SR_23Y
SR_23Y10M
SR_23Y11M
SR_23Y1M
SR_23Y2M
SR_23Y3M
SR_23Y4M
SR_23Y5M
SR_23Y6M
SR_23Y7M
SR_23Y8M
SR_23Y9M
SR_24Y
SR_24Y10M
SR_24Y11M
SR_24Y1M
SR_24Y2M
SR_24Y3M
SR_24Y4M
SR_24Y5M
SR_24Y6M
SR_24Y7M
SR_24Y8M
SR_24Y9M
SR_25Y
SR_25Y10M
SR_25Y11M
SR_25Y1M
SR_25Y2M
SR_25Y3M
SR_25Y4M
SR_25Y5M
SR_25Y6M
SR_25Y7M
SR_25Y8M
SR_25Y9M
SR_26Y
SR_26Y10M
SR_26Y11M
SR_26Y1M
SR_26Y2M
SR_26Y3M
SR_26Y4M
SR_26Y5M
SR_26Y6M
SR_26Y7M
SR_26Y8M
SR_26Y9M
SR_27Y
SR_27Y10M
SR_27Y11M
SR_27Y1M
SR_27Y2M
SR_27Y3M
SR_27Y4M
SR_27Y5M
SR_27Y6M
SR_27Y7M
SR_27Y8M
SR_27Y9M
SR_28Y
SR_28Y10M
SR_28Y11M
SR_28Y1M
SR_28Y2M
SR_28Y3M
SR_28Y4M
SR_28Y5M
SR_28Y6M
SR_28Y7M
SR_28Y8M
SR_28Y9M
SR_29Y
SR_29Y10M
SR_29Y11M
SR_29Y1M
SR_29Y2M
SR_29Y3M
SR_29Y4M
SR_29Y5M
SR_29Y6M
SR_29Y7M
SR_29Y8M
SR_29Y9M
SR_2Y
SR_2Y10M
SR_2Y11M
SR_2Y1M
SR_2Y2M
SR_2Y3M
SR_2Y4M
SR_2Y5M
SR_2Y6M
SR_2Y7M
SR_2Y8M
SR_2Y9M
SR_30Y
SR_3M
SR_3Y
SR_3Y10M
SR_3Y11M
SR_3Y1M
SR_3Y2M
SR_3Y3M
SR_3Y4M
SR_3Y5M
SR_3Y6M
SR_3Y7M
SR_3Y8M
SR_3Y9M
SR_4M
SR_4Y
SR_4Y10M
SR_4Y11M
SR_4Y1M
SR_4Y2M
SR_4Y3M
SR_4Y4M
SR_4Y5M
SR_4Y6M
SR_4Y7M
SR_4Y8M
SR_4Y9M
SR_5M
SR_5Y
SR_5Y10M
SR_5Y11M
SR_5Y1M
SR_5Y2M
SR_5Y3M
SR_5Y4M
SR_5Y5M
SR_5Y6M
SR_5Y7M
SR_5Y8M
SR_5Y9M
SR_6M
SR_6Y
SR_6Y10M
SR_6Y11M
SR_6Y1M
SR_6Y2M
SR_6Y3M
SR_6Y4M
SR_6Y5M
SR_6Y6M
SR_6Y7M
SR_6Y8M
SR_6Y9M
SR_7M
SR_7Y
SR_7Y10M
SR_7Y11M
SR_7Y1M
SR_7Y2M
SR_7Y3M
SR_7Y4M
SR_7Y5M
SR_7Y6M
SR_7Y7M
SR_7Y8M
SR_7Y9M
SR_8M
SR_8Y
SR_8Y10M
SR_8Y11M
SR_8Y1M
SR_8Y2M
SR_8Y3M
SR_8Y4M
SR_8Y5M
SR_8Y6M
SR_8Y7M
SR_8Y8M
SR_8Y9M
SR_9M
SR_9Y
SR_9Y10M
SR_9Y11M
SR_9Y1M
SR_9Y2M
SR_9Y3M
SR_9Y4M
SR_9Y5M
SR_9Y6M
SR_9Y7M
SR_9Y8M
SR_9Y9M
TAU1
TAU2

In [11]:
df_filtered = df_filtered[df_filtered['DATA_TYPE_FM'].astype(str).str.strip().str.startswith('SR_')]

In [12]:
unique_values = df_filtered['DATA_TYPE_FM'].unique()
for i in range(len(unique_values)):
    print(unique_values[i])

SR_10M
SR_10Y
SR_10Y10M
SR_10Y11M
SR_10Y1M
SR_10Y2M
SR_10Y3M
SR_10Y4M
SR_10Y5M
SR_10Y6M
SR_10Y7M
SR_10Y8M
SR_10Y9M
SR_11M
SR_11Y
SR_11Y10M
SR_11Y11M
SR_11Y1M
SR_11Y2M
SR_11Y3M
SR_11Y4M
SR_11Y5M
SR_11Y6M
SR_11Y7M
SR_11Y8M
SR_11Y9M
SR_12Y
SR_12Y10M
SR_12Y11M
SR_12Y1M
SR_12Y2M
SR_12Y3M
SR_12Y4M
SR_12Y5M
SR_12Y6M
SR_12Y7M
SR_12Y8M
SR_12Y9M
SR_13Y
SR_13Y10M
SR_13Y11M
SR_13Y1M
SR_13Y2M
SR_13Y3M
SR_13Y4M
SR_13Y5M
SR_13Y6M
SR_13Y7M
SR_13Y8M
SR_13Y9M
SR_14Y
SR_14Y10M
SR_14Y11M
SR_14Y1M
SR_14Y2M
SR_14Y3M
SR_14Y4M
SR_14Y5M
SR_14Y6M
SR_14Y7M
SR_14Y8M
SR_14Y9M
SR_15Y
SR_15Y10M
SR_15Y11M
SR_15Y1M
SR_15Y2M
SR_15Y3M
SR_15Y4M
SR_15Y5M
SR_15Y6M
SR_15Y7M
SR_15Y8M
SR_15Y9M
SR_16Y
SR_16Y10M
SR_16Y11M
SR_16Y1M
SR_16Y2M
SR_16Y3M
SR_16Y4M
SR_16Y5M
SR_16Y6M
SR_16Y7M
SR_16Y8M
SR_16Y9M
SR_17Y
SR_17Y10M
SR_17Y11M
SR_17Y1M
SR_17Y2M
SR_17Y3M
SR_17Y4M
SR_17Y5M
SR_17Y6M
SR_17Y7M
SR_17Y8M
SR_17Y9M
SR_18Y
SR_18Y10M
SR_18Y11M
SR_18Y1M
SR_18Y2M
SR_18Y3M
SR_18Y4M
SR_18Y5M
SR_18Y6M
SR_18Y7M
SR_18Y8M
SR_18Y9M
SR_19Y
SR_19Y10M
SR_19Y11M
SR_19Y1M
SR_19Y2M
SR_19Y3M
SR_19Y4M
SR_19Y5M
SR_19Y6M
SR_19Y7M
SR_19Y8M
SR_19Y9M
SR_1Y
SR_1Y10M
SR_1Y11M
SR_1Y1M
SR_1Y2M
SR_1Y3M
SR_1Y4M
SR_1Y5M
SR_1Y6M
SR_1Y7M
SR_1Y8M
SR_1Y9M
SR_20Y
SR_20Y10M
SR_20Y11M
SR_20Y1M
SR_20Y2M
SR_20Y3M
SR_20Y4M
SR_20Y5M
SR_20Y6M
SR_20Y7M
SR_20Y8M
SR_20Y9M
SR_21Y
SR_21Y10M
SR_21Y11M
SR_21Y1M
SR_21Y2M
SR_21Y3M
SR_21Y4M
SR_21Y5M
SR_21Y6M
SR_21Y7M
SR_21Y8M
SR_21Y9M
SR_22Y
SR_22Y10M
SR_22Y11M
SR_22Y1M
SR_22Y2M
SR_22Y3M
SR_22Y4M
SR_22Y5M
SR_22Y6M
SR_22Y7M
SR_22Y8M
SR_22Y9M
SR_23Y
SR_23Y10M
SR_23Y11M
SR_23Y1M
SR_23Y2M
SR_23Y3M
SR_23Y4M
SR_23Y5M
SR_23Y6M
SR_23Y7M
SR_23Y8M
SR_23Y9M
SR_24Y
SR_24Y10M
SR_24Y11M
SR_24Y1M
SR_24Y2M
SR_24Y3M
SR_24Y4M
SR_24Y5M
SR_24Y6M
SR_24Y7M
SR_24Y8M
SR_24Y9M
SR_25Y
SR_25Y10M
SR_25Y11M
SR_25Y1M
SR_25Y2M
SR_25Y3M
SR_25Y4M
SR_25Y5M
SR_25Y6M
SR_25Y7M
SR_25Y8M
SR_25Y9M
SR_26Y
SR_26Y10M
SR_26Y11M
SR_26Y1M
SR_26Y2M
SR_26Y3M
SR_26Y4M
SR_26Y5M
SR_26Y6M
SR_26Y7M
SR_26Y8M
SR_26Y9M
SR_27Y
SR_27Y10M
SR_27Y11M
SR_27Y1M
SR_27Y2M
SR_27Y3M
SR_27Y4M
SR_27Y5M
SR_27Y6M
SR_27Y7M
SR_27Y8M
SR_27Y9M
SR_28Y
SR_28Y10M
SR_28Y11M
SR_28Y1M
SR_28Y2M
SR_28Y3M
SR_28Y4M
SR_28Y5M
SR_28Y6M
SR_28Y7M
SR_28Y8M
SR_28Y9M
SR_29Y
SR_29Y10M
SR_29Y11M
SR_29Y1M
SR_29Y2M
SR_29Y3M
SR_29Y4M
SR_29Y5M
SR_29Y6M
SR_29Y7M
SR_29Y8M
SR_29Y9M
SR_2Y
SR_2Y10M
SR_2Y11M
SR_2Y1M
SR_2Y2M
SR_2Y3M
SR_2Y4M
SR_2Y5M
SR_2Y6M
SR_2Y7M
SR_2Y8M
SR_2Y9M
SR_30Y
SR_3M
SR_3Y
SR_3Y10M
SR_3Y11M
SR_3Y1M
SR_3Y2M
SR_3Y3M
SR_3Y4M
SR_3Y5M
SR_3Y6M
SR_3Y7M
SR_3Y8M
SR_3Y9M
SR_4M
SR_4Y
SR_4Y10M
SR_4Y11M
SR_4Y1M
SR_4Y2M
SR_4Y3M
SR_4Y4M
SR_4Y5M
SR_4Y6M
SR_4Y7M
SR_4Y8M
SR_4Y9M
SR_5M
SR_5Y
SR_5Y10M
SR_5Y11M
SR_5Y1M
SR_5Y2M
SR_5Y3M
SR_5Y4M
SR_5Y5M
SR_5Y6M
SR_5Y7M
SR_5Y8M
SR_5Y9M
SR_6M
SR_6Y
SR_6Y10M
SR_6Y11M
SR_6Y1M
SR_6Y2M
SR_6Y3M
SR_6Y4M
SR_6Y5M
SR_6Y6M
SR_6Y7M
SR_6Y8M
SR_6Y9M
SR_7M
SR_7Y
SR_7Y10M
SR_7Y11M
SR_7Y1M
SR_7Y2M
SR_7Y3M
SR_7Y4M
SR_7Y5M
SR_7Y6M
SR_7Y7M
SR_7Y8M
SR_7Y9M
SR_8M
SR_8Y
SR_8Y10M
SR_8Y11M
SR_8Y1M
SR_8Y2M
SR_8Y3M
SR_8Y4M
SR_8Y5M
SR_8Y6M
SR_8Y7M
SR_8Y8M
SR_8Y9M
SR_9M
SR_9Y
SR_9Y10M
SR_9Y11M
SR_9Y1M
SR_9Y2M
SR_9Y3M
SR_9Y4M
SR_9Y5M
SR_9Y6M
SR_9Y7M
SR_9Y8M
SR_9Y9M

In [13]:
df_filtered = df_filtered[df_filtered['DATA_TYPE_FM'].str.match(r'^SR_([0-9]|10)Y$')]

In [14]:
unique_values = df_filtered['DATA_TYPE_FM'].unique()
for i in range(len(unique_values)):
    print(unique_values[i])

SR_10Y
SR_1Y
SR_2Y
SR_3Y
SR_4Y
SR_5Y
SR_6Y
SR_7Y
SR_8Y
SR_9Y

In [15]:
df_filtered.tail(50)

        TIME_PERIOD DATA_TYPE_FM  OBS_VALUE
5558958  2024-10-18        SR_9Y   2.238138
5558959  2024-10-21        SR_9Y   2.323945
5558960  2024-10-22        SR_9Y   2.340794
5558961  2024-10-23        SR_9Y   2.372310
5558962  2024-10-24        SR_9Y   2.312664
5558963  2024-10-25        SR_9Y   2.340543
5558964  2024-10-28        SR_9Y   2.324523
5558965  2024-10-29        SR_9Y   2.377340
5558966  2024-10-30        SR_9Y   2.422218
5558967  2024-10-31        SR_9Y   2.474053
5558968  2024-11-01        SR_9Y   2.440010
5558969  2024-11-04        SR_9Y   2.441117
5558970  2024-11-05        SR_9Y   2.451877
5558971  2024-11-06        SR_9Y   2.458687
5558972  2024-11-07        SR_9Y   2.470810
5558973  2024-11-08        SR_9Y   2.419920
5558974  2024-11-11        SR_9Y   2.391512
5558975  2024-11-12        SR_9Y   2.379802
5558976  2024-11-13        SR_9Y   2.426492
5558977  2024-11-14        SR_9Y   2.398916
5558978  2024-11-15        SR_9Y   2.408601
5558979  2024-11-18        SR_9Y   2.426459
5558980  2024-11-19        SR_9Y   2.382500
5558981  2024-11-20        SR_9Y   2.399197
5558982  2024-11-21        SR_9Y   2.349593
5558983  2024-11-22        SR_9Y   2.306472
5558984  2024-11-25        SR_9Y   2.254982
5558985  2024-11-26        SR_9Y   2.253922
5558986  2024-11-27        SR_9Y   2.218650
5558987  2024-11-28        SR_9Y   2.181833
5558988  2024-11-29        SR_9Y   2.141803
5558989  2024-12-02        SR_9Y   2.091799
5558990  2024-12-03        SR_9Y   2.083165
5558991  2024-12-04        SR_9Y   2.119392
5558992  2024-12-05        SR_9Y   2.155177
5558993  2024-12-06        SR_9Y   2.123771
5558994  2024-12-09        SR_9Y   2.141798
5558995  2024-12-10        SR_9Y   2.146657
5558996  2024-12-11        SR_9Y   2.155740
5558997  2024-12-12        SR_9Y   2.211399
5558998  2024-12-13        SR_9Y   2.278343
5558999  2024-12-16        SR_9Y   2.277504
5559000  2024-12-17        SR_9Y   2.263485
5559001  2024-12-18        SR_9Y   2.289422
5559002  2024-12-19        SR_9Y   2.355268
5559003  2024-12-20        SR_9Y   2.322920
5559004  2024-12-23        SR_9Y   2.351809
5559005  2024-12-24        SR_9Y   2.355345
5559006  2024-12-27        SR_9Y   2.383880
5559007  2024-12-30        SR_9Y   2.397214

In [16]:
df_filtered = pd.concat([
    df_filtered[df_filtered['DATA_TYPE_FM'] != 'SR_10Y'],
    df_filtered[df_filtered['DATA_TYPE_FM'] == 'SR_10Y']
], ignore_index=True)

In [17]:
df_filtered.head()

  TIME_PERIOD DATA_TYPE_FM  OBS_VALUE
0  2004-09-06        SR_1Y   2.298838
1  2004-09-07        SR_1Y   2.328891
2  2004-09-08        SR_1Y   2.346666
3  2004-09-09        SR_1Y   2.308988
4  2004-09-10        SR_1Y   2.271566

In [18]:
df_pivoted = df_filtered.pivot(index='TIME_PERIOD', columns='DATA_TYPE_FM', values='OBS_VALUE')

In [19]:
df_pivoted.head()

DATA_TYPE_FM,SR_10Y,SR_1Y,SR_2Y,SR_3Y,SR_4Y,SR_5Y,SR_6Y,SR_7Y,SR_8Y,SR_9Y
TIME_PERIOD,,,,,,,,,,
2004-09-06,4.209220,2.298838,2.641262,2.951578,3.223235,3.457222,3.657429,3.828505,3.974939,4.100712
2004-09-07,4.209626,2.328891,2.679766,2.987293,3.252486,3.479518,3.673463,3.839294,3.981472,4.103839
2004-09-08,4.228419,2.346666,2.706542,3.016998,3.282196,3.507894,3.699959,3.863753,4.003922,4.124390
2004-09-09,4.161872,2.308988,2.646224,2.945649,3.206136,3.430628,3.623456,3.789113,3.931745,4.054972
2004-09-10,4.120981,2.271566,2.589654,2.884699,3.146724,3.374729,3.571385,3.740559,3.886214,4.011975

In [20]:
def maturity_key(col):
    return int(col.split('_')[1][:-1])  # removes 'Y' from 'SR_1Y'

df_pivoted = df_pivoted.reindex(columns=sorted(df_pivoted.columns, key=maturity_key))

In [21]:
df_pivoted.head()

DATA_TYPE_FM,SR_1Y,SR_2Y,SR_3Y,SR_4Y,SR_5Y,SR_6Y,SR_7Y,SR_8Y,SR_9Y,SR_10Y
TIME_PERIOD,,,,,,,,,,
2004-09-06,2.298838,2.641262,2.951578,3.223235,3.457222,3.657429,3.828505,3.974939,4.100712,4.209220
2004-09-07,2.328891,2.679766,2.987293,3.252486,3.479518,3.673463,3.839294,3.981472,4.103839,4.209626
2004-09-08,2.346666,2.706542,3.016998,3.282196,3.507894,3.699959,3.863753,4.003922,4.124390,4.228419
2004-09-09,2.308988,2.646224,2.945649,3.206136,3.430628,3.623456,3.789113,3.931745,4.054972,4.161872
2004-09-10,2.271566,2.589654,2.884699,3.146724,3.374729,3.571385,3.740559,3.886214,4.011975,4.120981

In [22]:
dates_to_plot = ['2024-12-30', '2004-09-06', '2020-03-23']

In [23]:
df_pivoted.index = pd.to_datetime(df_pivoted.index)
df_subset = df_pivoted.loc[df_pivoted.index.isin(pd.to_datetime(dates_to_plot))]

In [24]:
fig = go.Figure()

for date in df_subset.index:
    fig.add_trace(go.Scatter(
        x=df_subset.columns,
        y=df_subset.loc[date],
        mode='lines+markers',
        name=date.strftime('%Y-%m-%d')
    ))

fig.update_layout(
    title="Yield Curves for Selected Dates",
    xaxis_title="Maturity",
    yaxis_title="OBS_VALUE",
    template="plotly_white"
)

fig.show()

# SR means Spot Rate (zero coupon yields)

In [25]:
df_pivoted.head()

DATA_TYPE_FM,SR_1Y,SR_2Y,SR_3Y,SR_4Y,SR_5Y,SR_6Y,SR_7Y,SR_8Y,SR_9Y,SR_10Y
TIME_PERIOD,,,,,,,,,,
2004-09-06,2.298838,2.641262,2.951578,3.223235,3.457222,3.657429,3.828505,3.974939,4.100712,4.209220
2004-09-07,2.328891,2.679766,2.987293,3.252486,3.479518,3.673463,3.839294,3.981472,4.103839,4.209626
2004-09-08,2.346666,2.706542,3.016998,3.282196,3.507894,3.699959,3.863753,4.003922,4.124390,4.228419
2004-09-09,2.308988,2.646224,2.945649,3.206136,3.430628,3.623456,3.789113,3.931745,4.054972,4.161872
2004-09-10,2.271566,2.589654,2.884699,3.146724,3.374729,3.571385,3.740559,3.886214,4.011975,4.120981

In [26]:
df_pivoted.to_csv("yield_curves.csv")

In [29]:
row = df_pivoted.loc["2020-01-02"]

In [ ]:
row = df_pivoted.loc["2020-01-02"]
a = {}
for i, j in enumerate(row):
    a[i + 1] = j

a

{1: -0.6348438249505346,
 2: -0.6221803698032793,
 3: -0.5868721967847708,
 4: -0.5369920666650585,
 5: -0.4786057555661376,
 6: -0.4161298145166392,
 7: -0.3526758848614579,
 8: -0.2903535675168553,
 9: -0.2305226328298015,
 10: -0.1739952290506492}

In [36]:
df = pd.read_csv("../data/yield_curves.csv", index_col=0)

df.head()

,SR_1Y,SR_2Y,SR_3Y,SR_4Y,SR_5Y,SR_6Y,SR_7Y,SR_8Y,SR_9Y,SR_10Y
TIME_PERIOD,,,,,,,,,,
2004-09-06,2.298838,2.641262,2.951578,3.223235,3.457222,3.657429,3.828505,3.974939,4.100712,4.209220
2004-09-07,2.328891,2.679766,2.987293,3.252486,3.479518,3.673463,3.839294,3.981472,4.103839,4.209626
2004-09-08,2.346666,2.706542,3.016998,3.282196,3.507894,3.699959,3.863753,4.003922,4.124390,4.228419
2004-09-09,2.308988,2.646224,2.945649,3.206136,3.430628,3.623456,3.789113,3.931745,4.054972,4.161872
2004-09-10,2.271566,2.589654,2.884699,3.146724,3.374729,3.571385,3.740559,3.886214,4.011975,4.120981